force-app/main/default/objects/Rental_Property__c/Rental_Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>PROP-{00000}</displayFormat>
        <label>Property Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Property__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua &amp; Deps</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rental_Property__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Rental_Property__c/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <label>Nickname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rental_Property__c/fields/Offer_Count__c.field-meta.xml
<CustomField>
    <fullName>Offer_Count__c</fullName>
    <label>Offer Count</label>
    <summaryForeignKey>Property_Offers__c.Property__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Rental_Property__c/fields/One_Bedroom_Start_Price__c.field-meta.xml
<CustomField>
    <fullName>One_Bedroom_Start_Price__c</fullName>
    <label>One Bedroom Start Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rental_Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rental_Property__c/fields/Studio_Start_Price__c.field-meta.xml
<CustomField>
    <fullName>Studio_Start_Price__c</fullName>
    <label>Studio Start Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rental_Property__c/fields/Two_Bedroom_Start_Price__c.field-meta.xml
<CustomField>
    <fullName>Two_Bedroom_Start_Price__c</fullName>
    <label>Two Bedroom Start Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rental_Property__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/reitPropertyDataHelper.cls
public with sharing class reitPropertyDataHelper {

    //Constructor
    public reitPropertyDataHelper() {
        //super
    }

    //Apex method to fetch REIT property data
    @AuraEnabled (cacheable=true)
    public static List<Rental_Property__c> getPropertyList(Integer lim) {
        List<Rental_Property__c> listToReturn = [SELECT Name,
                                                        Nickname__c,
                                                        Street_Address__c,
                                                        State__c,
                                                        City__c,
                                                        Country__c,
                                                        Unit__c,
                                                        Description__c,
                                                        Image__c,
                                                        Studio_Start_Price__c,
                                                        One_Bedroom_Start_Price__c,
                                                        Two_Bedroom_Start_Price__c,
                                                        Offer_Count__c
                                                FROM Rental_Property__c LIMIT :lim];
        return listToReturn;

    }
}